[tool.poetry]
name = "marshmallow_geojson"
version = "0.1.0"
description = "Marshmallow schema validation for GeoJson"
authors = ["Aliaksandr Vaskevich <vaskevic.an@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
marshmallow = "^3.8.0"
ujson = "^3.2.0"

[tool.poetry.dev-dependencies]
pytest = "^6.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
